// Generated by gencpp from file loam_velodyne_msg/NodeTransform.msg
// DO NOT EDIT!


#ifndef LOAM_VELODYNE_MSG_MESSAGE_NODETRANSFORM_H
#define LOAM_VELODYNE_MSG_MESSAGE_NODETRANSFORM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

namespace loam_velodyne_msg
{
template <class ContainerAllocator>
struct NodeTransform_
{
  typedef NodeTransform_<ContainerAllocator> Type;

  NodeTransform_()
    : matchingResult(0), loopResult(0) {
    }
  NodeTransform_(const ContainerAllocator& _alloc)
    : matchingResult(0),loopResult(0)  {
  (void)_alloc;
    }



   typedef int32_t _matchingResult_type;
  _matchingResult_type matchingResult;
   typedef int32_t _loopResult_type;
  _loopResult_type loopResult;




  typedef boost::shared_ptr< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> const> ConstPtr;

}; // struct NodeTransform_

typedef ::loam_velodyne_msg::NodeTransform_<std::allocator<void> > NodeTransform;

typedef boost::shared_ptr< ::loam_velodyne_msg::NodeTransform > NodeTransformPtr;
typedef boost::shared_ptr< ::loam_velodyne_msg::NodeTransform const> NodeTransformConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loam_velodyne_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'loam_velodyne_msg': ['/home/slam/catkin_velodyne/src/loam_velodyne_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7507def70ac879c1e125f61f4cbf161";
  }

  static const char* value(const ::loam_velodyne_msg::NodeTransform_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7507def70ac879cULL;
  static const uint64_t static_value2 = 0x1e125f61f4cbf161ULL;
};

template<class ContainerAllocator>
struct DataType< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loam_velodyne_msg/NodeTransform";
  }

  static const char* value(const ::loam_velodyne_msg::NodeTransform_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 matchingResult\n\
";
  }

  static const char* value(const ::loam_velodyne_msg::NodeTransform_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.matchingResult);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeTransform_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loam_velodyne_msg::NodeTransform_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loam_velodyne_msg::NodeTransform_<ContainerAllocator>& v)
  {
    s << indent << "matchingResult: ";
    Printer<int32_t>::stream(s, indent + "  ", v.matchingResult);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOAM_VELODYNE_MSG_MESSAGE_NODETRANSFORM_H
